Web/Controllers/CategoriesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Database.Models.Songs;
using Microsoft.AspNetCore.Authorization;

namespace Web.Controllers
{
    /// <summary>
    ///     Controller for categories pages.
    /// </summary>
    public class CategoriesController : Controller
    {
        private readonly SongsDbContext _context;

        public CategoriesController(SongsDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        /// <summary>
        ///     Controller GET method to get page with a list of all categories.
        /// </summary>
        /// <returns>View of categories Index page.</returns>
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        /// <summary>
        ///     Controller GET method to get detail page of category according to specified ID.
        /// </summary>
        /// <param name="id">ID of category which detail page will be displayed.</param>
        /// <returns>View of category detail page</returns>
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        /// <summary>
        ///     Controller GET method to get page for creating of new Cateogry.
        /// </summary>
        /// <returns>View of category create page</returns>
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        ///     Controller POST method to store newly created category.
        /// </summary>
        /// <param name="category">Data of newly created category.</param>
        /// <returns>When everything goes OK, redirection to Index page, otherwise page to create the same category.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Name,Description")] Category category)
        {
            if (ModelState.IsValid)
            {
                category.LastModifiedDateTimeLocal = DateTime.Now.ToLocalTime();
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        /// <summary>
        ///     Controller GET method to get page for editing of category specified by ID.
        /// </summary>
        /// <param name="id">ID of category to be edited</param>
        /// <returns>View of categories edit page</returns>
        [Authorize]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        ///     Controller POST method to store changes made by editing.
        /// </summary>
        /// <param name="id">ID of category to be edited.</param>
        /// <param name="category">Data of edited category.</param>
        /// <returns>When everything goes OK, redirection to Index page, otherwise page to edit the same category.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,Description,LastModified")]
            Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    category.LastModifiedDateTimeLocal = DateTime.Now.ToLocalTime();
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        // GET: Categories/Delete/5
        /// <summary>
        ///     Controller GET method to get page to confirm deletion of a category specified by ID.
        /// </summary>
        /// <param name="id">ID of category to be removed.</param>
        /// <returns>View of category delete page.</returns>
        [Authorize]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        /// <summary>
        ///     Controller POST method to remove category specified by ID.
        /// </summary>
        /// <param name="id">ID of category to be deleted.</param>
        /// <returns>Redirection to categories Index page.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(long id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Web/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Database.Models.Songs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Models;

namespace Web.Controllers
{
    /// <summary>
    ///     Controller for song pages.
    /// </summary>
    public class SongsController : Controller
    {
        private readonly SongsDbContext _context;

        public SongsController(SongsDbContext context)
        {
            _context = context;
        }

        // GET: Songs
        /// <summary>
        ///     Controller GET method to get page with a list of all songs.
        /// </summary>
        /// <returns>View of Songs Index page</returns>
        public async Task<IActionResult> Index()
        {
            var viewModel = new SongsTableViewModel
            {
                ViewMode = SongsTableViewModel.Mode.Maintaining,
                Songs = await _context.Songs
                    .Include(song => song.SongCategories).ThenInclude(songCategory => songCategory.Category)
                    .OrderBy(s => s.Title.ToLower()).ToListAsync(),
                Categories = await _context.Categories
                    .OrderBy(c => c.Name.ToLower())
                    .ToListAsync()
            };

            return View(viewModel);
        }

        // GET: Songs/Details/5
        /// <summary>
        ///     Controller GET method to get detail page of song according to specified ID.
        /// </summary>
        /// <param name="id">ID of song which detail page will be displayed</param>
        /// <returns>View of songs detail page</returns>
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null) return NotFound();

            var song = await _context.Songs
                .Include(s => s.Verses)
                .Include(s => s.SongCategories).ThenInclude(songCategory => songCategory.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null) return NotFound();

            song.Verses = song.Verses.OrderBy(v => v.SequenceNumber).ToList();

            return View(song);
        }

        // GET: Songs/Create
        /// <summary>
        ///     Controller GET method to get page for creating of new Song.
        /// </summary>
        /// <returns>View of songs create page</returns>
        [Authorize]
        public IActionResult Create()
        {
            var viewModel = new SongEditViewModel
            {
                Song = new Song(),
                OtherCategories = _context.Categories
                    .OrderBy(c => c.Name.ToLower())
                    .ToList(),
                SelectedCategories = new List<Category>()
            };

            viewModel.Song.Verses.Add(new Verse());

            return View(viewModel);
        }

        // POST: Songs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        ///     Controller POST method to store newly created song.
        /// </summary>
        /// <param name="viewModel">Data of newly created song.</param>
        /// <returns>When everything goes OK, redirection to Index page, otherwise page to create the same song.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Song,SelectedCategories")] SongEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.SelectedCategories != null)
                {
                    foreach (var category in viewModel.SelectedCategories)
                    {
                        viewModel.Song.SongCategories.Add(new SongCategory
                        {
                            Song = viewModel.Song,
                            CategoryId = category.Id
                        });
                    }
                }

                viewModel.Song.LastModifiedDateTimeLocal = DateTime.Now.ToLocalTime();

                _context.Songs.Add(viewModel.Song);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        // GET: Songs/Edit/5
        /// <summary>
        ///     Controller GET method to get page for editing of song specified by ID.
        /// </summary>
        /// <param name="id">ID of song to be edited</param>
        /// <returns>View of songs edit page</returns>
        [Authorize]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null) return NotFound();

            var viewModel = new SongEditViewModel
            {
                Song = await _context.Songs
                    .Include(s => s.Verses)
                    .Include(s => s.SongCategories).ThenInclude(songCategory => songCategory.Category)
                    .FirstOrDefaultAsync(m => m.Id == id),
                OtherCategories = await _context.Categories
                    .OrderBy(c => c.Name.ToLower())
                    .ToListAsync()
            };
            if (viewModel.Song == null) return NotFound();

            viewModel.Song.Verses = viewModel.Song.Verses.OrderBy(v => v.SequenceNumber).ToList();

            viewModel.SelectedCategories = new List<Category>();
            foreach (var songCategory in viewModel.Song.SongCategories)
            {
                viewModel.OtherCategories.Remove(songCategory.Category);
                viewModel.SelectedCategories.Add(songCategory.Category);
            }

            return View(viewModel);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        ///     Controller POST method to store changes made by editing.
        /// </summary>
        /// <param name="id">ID of song to be edited</param>
        /// <param name="viewModel">Data of edited song</param>
        /// <returns>When everything goes OK, redirection to Index page, otherwise page to edit the same song.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(
            long id,
            [Bind("Song,SelectedCategories")] SongEditViewModel viewModel)
        {
            if (id != viewModel.Song.Id) return NotFound();

            if (ModelState.IsValid)
            {
                if (viewModel.SelectedCategories != null)
                {
                    foreach (var category in viewModel.SelectedCategories)
                    {
                        viewModel.Song.SongCategories.Add(new SongCategory
                            {SongId = viewModel.Song.Id, CategoryId = category.Id});
                    }
                }

                try
                {
                    _context.UpdateSongWithVersesAndCategories(viewModel.Song);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongExists(viewModel.Song.Id))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        // GET: Songs/Delete/5
        /// <summary>
        ///     Controller GET method to get page to confirm deletion of a song specified by ID.
        /// </summary>
        /// <param name="id">ID of song to be removed</param>
        /// <returns>View of songs delete page.</returns>
        [Authorize]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null) return NotFound();

            var song = await _context.Songs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null) return NotFound();

            return View(song);
        }

        // POST: Songs/Delete/5
        /// <summary>
        ///     Controller POST method to remove song specified by ID.
        /// </summary>
        /// <param name="id">ID of song to be deleted.</param>
        /// <returns>Redirection to songs Index page.</returns>
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var song = await _context.Songs
                .Include(s => s.Verses)
                .Include(s => s.SongCategories)
                .Include(s => s.SongPlaylists)
                .FirstOrDefaultAsync(m => m.Id == id);

            _context.Songs.Remove(song);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private bool SongExists(long id)
        {
            return _context.Songs.Any(e => e.Id == id);
        }
    }
}

Web/Views/Shared/_AllSongsTablePartial.cshtml
@model AllSongsAllCategoriesViewModel


<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Songs[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Songs[0].Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Songs[0].SongCategories)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Songs[0].Author)
        </th>
        <th class="text-right">
            <a class="btn btn-success btn-sm " asp-action="Create">
                <img src="~/img/plus-2-16.png" alt="Vytvoriť novú pieseň" class="img-in-button">
            </a>
        </th>
    </tr>
    <tr>
        <th>
            <input id="titleFilterInput" type="text" class=" input-filter js-filter" 
                   placeholder="Zadajte filter">
        </th>
        <th>
            <input id="numberFilterInput" type="number" class="input-filter js-filter"
                   placeholder="Zadajte filter">
        </th>
        <th>
            <select class="input-filter js-filter" id="categoryFilterSelect" >
                <option value="">Zvoľte filter</option>
                @foreach (var category in Model.Categories)
                {
                    <option value=@category.Id>@category.Name</option>
                }
            </select>
        </th>
        <th>
            <input id="authorFilterInput" type="text" class="input-filter js-filter"
                   placeholder="Zadajte filter">
        </th>
        <th class="text-right">
            <button id="clearFilterButton" class="btn btn-light btn-sm " type="button"> 
                <img src="~/img/x-mark-dark-16.png" alt="Vytvoriť novú pieseň" class="img-in-button">
            </button>
        </th>
    </tr>
    </thead>
    <tbody id="songTableBody">
@foreach (var song in Model.Songs) {
        <tr>
            <td class="js-title">
                @Html.DisplayFor(modelItem => song.Title)
            </td>
            <td class="js-song-number">
                @Html.DisplayFor(modelItem => song.Number)
            </td>
            <td style="width: min-content" class="js-categories">
                <div>
                    @foreach (var songCategory in song.SongCategories)
                    {
                        
                        <span class="badge badge-primary js-category">
                            <p hidden class="js-category-id">@songCategory.CategoryId</p>
                            @songCategory.Category.Name
                        </span>
                    }    
                </div>
            </td>
            <td class="js-author">
                @Html.DisplayFor(modelItem => song.Author)
            </td>
            <td class="text-right">
                <div class="btn-group btn-group-sm">
                    <a class="btn btn-info" asp-action="Edit" asp-route-id="@song.Id">
                        <img src="~/img/pencil-16.png" alt="Upraviť" class="img-in-button">
                    </a>
                    <a class="btn btn-secondary" asp-action="Details" asp-route-id="@song.Id">
                        <img src="~/img/view-details-16.png" alt="Detaily" class="img-in-button">
                    </a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@song.Id">
                        <img src="~/img/trash-2-16.png" alt="Odstrániť" class="img-in-button">
                    </a>
                </div>
                
            </td>
        </tr>
}
    </tbody>
</table>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script>
$(document).ready(function(){
    $.expr[':'].textEquals = $.expr.createPseudo(function(arg) {
        return function( elem ) {
            return $(elem).text().match("^" + arg + "$");
        };
    });
    
    
    $(".js-filter").on("change keyup", function() {
        filter();
    });
    
    $("#clearFilterButton").on("click", function() {
        $('#titleFilterInput').val('');
        $('#numberFilterInput').val('');
        $('#authorFilterInput').val('');
        $('#categoryFilterSelect').val($("#categoryFilterSelect option:first").val());
        
        
        $("#songTableBody tr").each(function() {
            $(this).toggle(true)
        });
    }); 
    
    function filter() {
        let titleFilterValue = $('#titleFilterInput').val().toLowerCase();
        let numberFilterValue = $('#numberFilterInput').val().toLowerCase();
        let authorFilterValue = $('#authorFilterInput').val().toLowerCase();
        let categoryFilterId = $('#categoryFilterSelect').find(':selected').val();
      
        $("#songTableBody tr").each(function() {
            $(this).toggle(
                $(this).find('.js-title').text().toLowerCase().indexOf(titleFilterValue) > -1 &&
                $(this).find('.js-author').text().toLowerCase().indexOf(authorFilterValue) > -1 &&
                $(this).find('.js-song-number').text().toLowerCase().indexOf(numberFilterValue) > -1 &&
                (categoryFilterId === "" || $(this).find(".js-category-id:contains('" + categoryFilterId + "')").length > 0)
                ) 
        });
    }
 
});
</script>

Web/Views/Shared/_CategoriesAddingPartial.cshtml
@model Web.Models.SongEditViewModel

<hr/>
<div class="form-group ">
    <div class="form-inline">
        <label asp-for="Song.SongCategories" class="control-label h5"></label>
        <button class="btn btn-success btn-sm float-right js-btn-add-category" type="button" style="margin-left: 10px"
                data-toggle="modal" data-target="#addCategoryModal">
            <i class="fa fa-plus" aria-hidden="true"></i>
        </button>
    </div>

    <div class="control-label" style="margin-top: 10px">
        <h5 id="selectedCategories">
            @for (int i = 0; i < Model.Song.SongCategories.Count; i++)
            {
                <span class="badge badge-primary js-category">
                    @Model.SelectedCategories[i].Name
                    <input type="hidden" asp-for="SelectedCategories[i].Id" class="js-cat-id"/>
                    <input type="hidden" asp-for="SelectedCategories[i].Name" class="js-cat-name"/>

                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                </span>
            }
        </h5>
    </div>

</div>
<hr/>


<!-- Modal -->
<div class="modal fade" id="addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Pridať kategóriu</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 id="otherCategories">
                    @for (int i = 0; i < Model.OtherCategories.Count; i++)
                    {
                        <span class="badge badge-primary js-category">
                            @Model.OtherCategories[i].Name
                            <input type="hidden" asp-for="OtherCategories[i].Id" class="js-cat-id"/>
                            <input type="hidden" asp-for="OtherCategories[i].Name" class="js-cat-name"/>

                            <i class="fa fa-plus" aria-hidden="true"></i>
                        </span>
                    }
                </h5>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script>

    $(document).ready(function () {  
        $(document).on('click', '.js-category-remove', function () {
            let clone = $(this).parent('.js-category').clone();   
            $(this).parent('.js-category').remove();
            
            $("#otherCategories")
                .append(' ')
                .append(clone); // add to other (not selected) categories
            renameCategoriesTags();
        });
        
        $(document).on('click', '.js-category-add', function () {
            let clone = $(this).parent('.js-category').clone();   
            $(this).parent('.js-category').remove();
            
            $("#selectedCategories")
                .append(' ')    
                .append(clone);    // add to selected categories
            renameCategoriesTags()
        });
        
        function renameCategoriesTags() {
            $("#selectedCategories").find(".js-category").each(function(i) {
                $(this).find(".js-cat-id")
                    .attr('id', 'SelectedCategories_' + i + '__Id')
                    .attr('name', 'SelectedCategories[' + i + '].Id');
                
                $(this).find(".js-cat-name")
                    .attr('id', 'SelectedCategories_' + i + '__Name')
                    .attr('name', 'SelectedCategories[' + i + '].Name');
                
                $(this).find(".js-category-add")                    // if bad button -> change it
                                .attr('class', 'js-category-remove')
                                .attr('src', '/img/x-mark-12.png')
                                .attr('alt', 'Vymazať kategóriu');
            });
            
            $("#otherCategories").find(".js-category").each(function(i) {
                $(this).find(".js-cat-id")
                    .attr('id', 'OtherCategories_' + i + '__Id')
                    .attr('name', 'OtherCategories[' + i + '].Id');
                
                $(this).find(".js-cat-name")
                    .attr('id', 'OtherCategories_' + i + '__Name')
                    .attr('name', 'OtherCategories[' + i + '].Name');
                
                $(this).find(".js-category-remove")                 // if bad button -> change it
                                .attr('class', 'js-category-add')
                                .attr('src', '/img/plus-2-12.png')
                                .attr('alt', 'Pridať kategóriu');
            });
        }
    });
</script>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="sk">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EKS</title>
    <link rel="shortcut icon" href="~/img/main_icon_dark.svg" type="image/x-icon" />
    @* <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"> *@

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
<header>
    <nav class="my-header navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
        <div class="container">
            <img src="~/img/main_icon_light.svg" alt="Eks Logo" width="40"/>
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EKS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">

                    @*<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Domov</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Songs" asp-action="Index">Piesne</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index">Kategórie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Playlists" asp-action="Index">Playlisty</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<section class="">
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
</section>

<footer class="footer border-top text-light">
    <div class="container-fluid">
        <div class="eks-copyright">&copy;JosoP 2019 - EKS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></div>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>